### PR TITLE
UI

### PR DESCRIPTION
**Pull request by mohammadkhizerkhan**
-installed and added tailwind configs
-added logo
-added quiz cards
-added quiz question UI
-added login page

### CODE REVIEW

**Comment by Nishant-96** [comment]
https://c.tenor.com/0nl5HQ4PLpUAAAAC/mirzapur-chiii.gif

**Comment by Nishant-96** [comment]
indexddd

**Review by muskaanshah — APPROVED** [review]
UI looks good, I like the logo
Good folder structure
One suggestion - use a little darker shade of green since contrast ratio is a little on the lower side, it's difficult to read the heading

**Review by Nishant-96 — APPROVED** [review]
- Easily understandable code
- liked the UI

**Comment by saketkum11** [comment]
- clean code
- UI is clear
- much to understand code
- short PR is great

**Pull request merged**
